### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by sarumie** [sarumie/VizMem#1]
- [x] add sfx when click
- [x] set btn to different color when playing/stopped
- [x] add icon
- [x] make tiles dynamic incrementallty
